[package]
name = "hexeline"
version = "0.1.0"
authors = ["Jason Lingle <jason@lin.gl>"]

[dependencies]
arrayvec = { version = "0.3.23", features = ["use_union"] }
cgmath = { version = "0.14.1", features = ["use_simd"] }
env_logger = "0.4.3"
fnv = "1.0.5"
gl = "0.6.3"
log = "0.3.8"
png = "0.7.0"
sdl2 = "0.30.0"
simd = "0.2.0"
smallvec = "0.4.1"

[dev-dependencies]
proptest = "0.2.0"

[profile.test]
opt-level = 1

[profile.bench]
debug = 2
