[package]
name = "hexeline"
version = "0.1.0"
authors = ["Jason Lingle <jason@lin.gl>"]

[dependencies]
sdl2 = "0.16.1"
# Vendored in src/glium_sdl2 since upstream is behind the current SDL version.
# glium_sdl2 = "0.10.0"
glium_text = "0.8.0"
libc = "0.2.7"
nalgebra = "0.5.1"

[dependencies.glium]
version = "0.13.5"
default-features = false
